# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_analyst', models.BooleanField()),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reqman.Analyst')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('connection_details', models.CharField(max_length=30)),
                ('maintained_stakeholder', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('date_requested', models.DateField()),
                ('date_released', models.DateField()),
                ('analysts', models.ManyToManyField(through='reqman.Contribution', to='reqman.Analyst')),
                ('databases', models.ManyToManyField(to='reqman.Database')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reqman.Stakeholder'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reqman.Request'),
        ),
    ]
