# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='email',
            field=models.CharField(default='me@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='phone_number',
            field=models.CharField(default='613-233-2098', max_length=30),
            preserve_default=False,
        ),
    ]
